language: ruby
cache: bundler

addons:
  code_climate:
    repo_token: a2a9d06575f1e096805e0fe260e3f0c7e740e23de2a89afe7d07761e486ac5a1

rvm:
  - 2.1.6
  - 2.2.2

script: 'bundle exec rake spec'

notifications:
  email:
    recipients:
      - eturino@eturino.com
    on_failure: change
    on_success: never
